#!/bin/sh

set -e

NETCDF=netcdf-4.2.1.1
NETCDF_WIN="$( cd "$( dirname "$0" )" && pwd )"
BINARIES=$NETCDF_WIN/bin

# Reset to known state

echo "# Resetting NetCDF sources to clean state"

cd $NETCDF_WIN
rm -rf $NETCDF
tar -zxvf $NETCDF.tar.gz
cd $NETCDF


# Generate stdcall wrappers

echo
echo "# Generating stdcall wrappers"

runghc $NETCDF_WIN/mkstdcall.hs \
	--exclude=$NETCDF_WIN/netcdf.ignore \
	include/netcdf.h > \
	liblib/stdcall.c

patch liblib/Makefile.am $NETCDF_WIN/liblib-Makefile.am.patch


# Configure NetCDF

echo
echo "# Configuring NetCDF"

autoreconf -i
./configure --enable-dll --disable-netcdf-4
patch config.h $NETCDF_WIN/config.h.patch


# Build NetCDF

echo
echo "# Building NetCDF"

make

# Harvest Binaries

echo
echo "# Harvesting Binaries"

rm -rf $BINARIES
mkdir $BINARIES

cp include/netcdf.h             $BINARIES/netcdf.h
cp liblib/netcdfdll.def         $BINARIES/netcdf.def
cp liblib/.libs/libnetcdf-7.dll $BINARIES/netcdf.dll
dlltool --input-def=$BINARIES/netcdf.def \
        --dllname=netcdf.dll   \
        --output-lib=$BINARIES/netcdf.lib
